insert into authors (id, first_name, last_name) values (1, 'Burtie', 'Bullimore');
insert into authors (id, first_name, last_name) values (2, 'Letizia', 'Bonin');
insert into authors (id, first_name, last_name) values (3, 'Trixie', 'Diffley');
insert into authors (id, first_name, last_name) values (4, 'Helli', 'MacCleod');
insert into authors (id, first_name, last_name) values (5, 'Tammy', 'Ingray');
insert into authors (id, first_name, last_name) values (6, 'Augy', 'D''Enrico');
insert into authors (id, first_name, last_name) values (7, 'Rochelle', 'Durbyn');
insert into authors (id, first_name, last_name) values (8, 'Nat', 'Puckring');
insert into authors (id, first_name, last_name) values (9, 'Byram', 'Shotter');
insert into authors (id, first_name, last_name) values (10, 'Terrye', 'Skrines');
insert into authors (id, first_name, last_name) values (11, 'Cherilynn', 'Donneely');
insert into authors (id, first_name, last_name) values (12, 'Cherri', 'Bellis');
insert into authors (id, first_name, last_name) values (13, 'Bathsheba', 'Claibourn');
insert into authors (id, first_name, last_name) values (14, 'Ainslie', 'Ciotti');
insert into authors (id, first_name, last_name) values (15, 'Bartholemy', 'Leyninye');
insert into authors (id, first_name, last_name) values (16, 'Roosevelt', 'MacGill');
insert into authors (id, first_name, last_name) values (17, 'Micheal', 'Snazel');
insert into authors (id, first_name, last_name) values (18, 'Lynnette', 'Neads');
insert into authors (id, first_name, last_name) values (19, 'Baxie', 'd''Arcy');
insert into authors (id, first_name, last_name) values (20, 'Urban', 'Stroud');
insert into authors (id, first_name, last_name) values (21, 'Jeralee', 'Collerd');

insert into books (id, price, price_old, title) values (1, 1243, 2666, 'Home Ing');
insert into books (id, price, price_old, title) values (2, 1955, 2989, 'Job');
insert into books (id, price, price_old, title) values (3, 348, 105, 'Solarbreeze');
insert into books (id, price, price_old, title) values (4, 2515, 2777, 'Matsoft');
insert into books (id, price, price_old, title) values (5, 964, 3474, 'Fintone');
insert into books (id, price, price_old, title) values (6, 2060, 1391, 'It');
insert into books (id, price, price_old, title) values (7, 1460, 405, 'Bytecard');
insert into books (id, price, price_old, title) values (8, 1454, 1685, 'Zontrax');
insert into books (id, price, price_old, title) values (9, 2290, 4835, 'Holdlamis');
insert into books (id, price, price_old, title) values (10, 1051, 3209, 'Voltsillam');
insert into books (id, price, price_old, title) values (11, 2916, 1858, 'Bitchip');
insert into books (id, price, price_old, title) values (12, 1332, 804, 'Aerified');
insert into books (id, price, price_old, title) values (13, 1886, 2171, 'Y-find');
insert into books (id, price, price_old, title) values (14, 2533, 4560, 'Daltfresh');
insert into books (id, price, price_old, title) values (15, 196, 3119, 'Regrant');
insert into books (id, price, price_old, title) values (16, 2870, 3471, 'Domainer');
insert into books (id, price, price_old, title) values (17, 2641, 1697, 'Duobam');
insert into books (id, price, price_old, title) values (18, 2987, 4312, 'Namfix');
insert into books (id, price, price_old, title) values (19, 2216, 3313, 'Zamit');
insert into books (id, price, price_old, title) values (20, 166, 1781, 'Kanlam');
insert into books (id, price, price_old, title) values (21, 1854, 203, 'Solarbreeze');
