insert into authors (id, description, name, photo, slug) values (1, 'Persevering intangible archive', 'Dannye Castana', 'http://dummyimage.com/224x100.png/cc0000/ffffff', 'Shandong University');
insert into authors (id, description, name, photo, slug) values (2, 'Reverse-engineered intangible architecture', 'Dulcinea Scamaden', 'http://dummyimage.com/204x100.png/5fa2dd/ffffff', 'Royal College of Art');
insert into authors (id, description, name, photo, slug) values (3, 'Optional national orchestration', 'Leland Francisco', 'http://dummyimage.com/164x100.png/5fa2dd/ffffff', 'Universidad Politécnica de Cataluna');
insert into authors (id, description, name, photo, slug) values (4, 'Automated tertiary portal', 'Armin Sime', 'http://dummyimage.com/215x100.png/5fa2dd/ffffff', 'Technical University of Czestochowa');
insert into authors (id, description, name, photo, slug) values (5, 'Cross-group mission-critical middleware', 'Woody Bryers', 'http://dummyimage.com/226x100.png/5fa2dd/ffffff', 'Ecole Supérieure Internationale d''Administration des Entreprises');
insert into authors (id, description, name, photo, slug) values (6, 'Streamlined tangible firmware', 'Vonni Petersen', 'http://dummyimage.com/119x100.png/5fa2dd/ffffff', 'Taejon University');
insert into authors (id, description, name, photo, slug) values (7, 'Reduced responsive internet solution', 'Lorry Van Salzberger', 'http://dummyimage.com/195x100.png/ff4444/ffffff', 'Antioch University Los Angeles');
insert into authors (id, description, name, photo, slug) values (8, 'Diverse discrete policy', 'Gillan Wrankmore', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 'Wisconsin School of Professional Psychology');
insert into authors (id, description, name, photo, slug) values (9, 'Virtual hybrid extranet', 'Ripley Kann', 'http://dummyimage.com/154x100.png/ff4444/ffffff', 'American University in Dubai');
insert into authors (id, description, name, photo, slug) values (10, 'Proactive clear-thinking Graphic Interface', 'Kelwin Hansmann', 'http://dummyimage.com/120x100.png/ff4444/ffffff', 'Instituto Tecnológico Metropolitano');
insert into authors (id, description, name, photo, slug) values (11, 'Streamlined empowering ability', 'Brandice Elven', 'http://dummyimage.com/147x100.png/dddddd/000000', 'Mount Vernon College');
insert into authors (id, description, name, photo, slug) values (12, 'Networked modular protocol', 'Xena Peskett', 'http://dummyimage.com/248x100.png/ff4444/ffffff', 'Universidad Argentina de la Empresa');
insert into authors (id, description, name, photo, slug) values (13, 'Stand-alone client-server task-force', 'Teddy Dummer', 'http://dummyimage.com/148x100.png/ff4444/ffffff', 'St. Petersburg State Medical Academy');
insert into authors (id, description, name, photo, slug) values (14, 'Balanced bottom-line hierarchy', 'Aland Paolini', 'http://dummyimage.com/151x100.png/dddddd/000000', 'Kendall College of Art and Design');
insert into authors (id, description, name, photo, slug) values (15, 'Organized explicit definition', 'Clayborn Marder', 'http://dummyimage.com/142x100.png/ff4444/ffffff', 'Theologische Hochschule Friedensau');
insert into authors (id, description, name, photo, slug) values (16, 'Customizable attitude-oriented hierarchy', 'Luise Mergue', 'http://dummyimage.com/208x100.png/dddddd/000000', 'Institute of Teachers Education, Penang');
insert into authors (id, description, name, photo, slug) values (17, 'Persevering radical emulation', 'Judah Please', 'http://dummyimage.com/236x100.png/5fa2dd/ffffff', 'Grace Bible College');
insert into authors (id, description, name, photo, slug) values (18, 'Expanded full-range product', 'Zelma Schindler', 'http://dummyimage.com/241x100.png/cc0000/ffffff', 'Akhbar El Yom Academy');
insert into authors (id, description, name, photo, slug) values (19, 'Distributed upward-trending monitoring', 'Lock Robertshaw', 'http://dummyimage.com/172x100.png/ff4444/ffffff', 'Universidad Nacional de San Agustin');
insert into authors (id, description, name, photo, slug) values (20, 'Stand-alone intermediate framework', 'Harland Matveiko', 'http://dummyimage.com/144x100.png/ff4444/ffffff', 'Nippon Medical School');
insert into authors (id, description, name, photo, slug) values (21, 'Expanded uniform software', 'Adena Beels', 'http://dummyimage.com/146x100.png/cc0000/ffffff', 'Saratov State Technical University');


insert into books (id, price, price_old, title) values (1, 1243, 2666, 'Home Ing');
insert into books (id, price, price_old, title) values (2, 1955, 2989, 'Job');
insert into books (id, price, price_old, title) values (3, 348, 105, 'Solarbreeze');
insert into books (id, price, price_old, title) values (4, 2515, 2777, 'Matsoft');
insert into books (id, price, price_old, title) values (5, 964, 3474, 'Fintone');
insert into books (id, price, price_old, title) values (6, 2060, 1391, 'It');
insert into books (id, price, price_old, title) values (7, 1460, 405, 'Bytecard');
insert into books (id, price, price_old, title) values (8, 1454, 1685, 'Zontrax');
insert into books (id, price, price_old, title) values (9, 2290, 4835, 'Holdlamis');
insert into books (id, price, price_old, title) values (10, 1051, 3209, 'Voltsillam');
insert into books (id, price, price_old, title) values (11, 2916, 1858, 'Bitchip');
insert into books (id, price, price_old, title) values (12, 1332, 804, 'Aerified');
insert into books (id, price, price_old, title) values (13, 1886, 2171, 'Y-find');
insert into books (id, price, price_old, title) values (14, 2533, 4560, 'Daltfresh');
insert into books (id, price, price_old, title) values (15, 196, 3119, 'Regrant');
insert into books (id, price, price_old, title) values (16, 2870, 3471, 'Domainer');
insert into books (id, price, price_old, title) values (17, 2641, 1697, 'Duobam');
insert into books (id, price, price_old, title) values (18, 2987, 4312, 'Namfix');
insert into books (id, price, price_old, title) values (19, 2216, 3313, 'Zamit');
insert into books (id, price, price_old, title) values (20, 166, 1781, 'Kanlam');
insert into books (id, price, price_old, title) values (21, 1854, 203, 'Solarbreeze');
